photon:
  network:
    host: 127.0.0.1
    broadcast-port: 7500
    receive-port: 7501
  game:
    start-countdown-length: 30
    game-length: 360
    points-player-tag: 10
    points-base-tag: 100
    music:
      volume: 1.0
      tracks:
        - "assets/audio/music/Track01.mp3"
        - "assets/audio/music/Track02.mp3"
        - "assets/audio/music/Track03.mp3"
        - "assets/audio/music/Track04.mp3"
        - "assets/audio/music/Track05.mp3"
        - "assets/audio/music/Track06.mp3"
        - "assets/audio/music/Track07.mp3"
        - "assets/audio/music/Track08.mp3"
    ui:
      fonts:
        header: "assets/fonts/Orbitron/static/Orbitron-Bold.ttf"
        default: null
database:
  db-name: photon
