photon:
  network:
    host: 127.0.0.1
    broadcast-port: 7500
    receive-port: 7501
  game:
    start-countdown-length: 30
    game-length: 360
    points-player-tag: 50
    points-base-tag: 100
database:
  db-name: photon
